### ISSUE TITLE
Charts for ember-osf-web

### ISSUE THREAD

**Issue by yacchin1205** [CenterForOpenScience/helm-charts#21]
I'm trying to deploy OSF services using charts in this repo. It seems that most of the features are working well, but *My Quick Files* says 404.

I assume that it is because there are no ember-osf-web in my deployments. (I'm using the charts `mongodb`, `postgresql`, `redis`, `rabbitmq`, `elasticsearch`, `osf`, `wb`, `mfr`, `cas`.)

Which chart should I use to deploy ember-osf-web?

**Comment by binoculars** [comment]
You need the `osf` chart and will need to configure web-local.py in the OSF and the proxy settings for it in the values file.

**Comment by yacchin1205** [comment]
@binoculars Thank you for your reply.

I have tried to configure web-local.py in the values file below.

```
        EXTERNAL_EMBER_APPS = {
            'ember_osf_web': {
                'url': '/ember_osf_web/',
                'server': 'http://localhost:4200',
                'path': '/ember_osf_web/'
            },
            ...
        }
```

Though, *My Quick Files* still said 404 ... It seems that `osf-osf-web` pod has no process listening on port 4200, and I assume that it is necessary to launch ember-osf-web (listening on port 4200) service using the another (maybe I am missing) chart.

How to deploy ember-osf-web? pod...?

**Comment by icereval** [comment]
the host in `'server': 'http://localhost:4200',` needs to be the value of your osf-web chart service name.

**Comment by binoculars** [comment]
In the `osf` values file:

```yaml
osf-web:
  enabled: true
  service:
    name: t1osfweb-osf-web
    externalPort: 80
```
...

web-local.py
```yaml
    EXTERNAL_EMBER_APPS = {
        # 'preprints': {
        #     'server': os.environ.get('OSF_PREPRINTS_URL', None),
        #     'path': '/preprints/',
        # },
        # 'registries': {
        #     'server': os.environ.get('OSF_REGISTRIES_URL', None),
        #     'path': '/registries/',
        # },
        # 'reviews': {
        #     'server': os.environ.get('OSF_REVIEWS_URL', None),
        #     'path': '/reviews/',
        # },
        'ember_osf_web': {
           'server': os.environ.get('OSF_WEB_URL', None),
           'path': '/ember_osf_web/',
        },
    }
```

the `OSF_WEB_URL` is mapped from:
https://github.com/CenterForOpenScience/helm-charts/blob/eaf309b2447f22a7628922332988b1892b7e591f/osf/templates/web-deployment.yaml#L188-L189

**Comment by yacchin1205** [comment]
Thanks @icereval @binoculars ! I missed osf-web chart and osf-web section in osf chart.

*My Quick Files* page has appeared by installing osf-web chart and configuring osf chart to enable osf-web service, although the page fails with error `http://localhost:8000/v2/users/me/ net::ERR_CONNECTION_REFUSED`.

It seems that my configuration about osf-web chart is insufficient  (especially https://github.com/CenterForOpenScience/ember-osf-web/blob/develop/config/environment.js#L20 has not been set)... Is there any examples of how to write values.yaml for osf-web chart?

**Comment by binoculars** [comment]
This is similar to what I sent @Yusuke-KOMIYAMA but for the `osf-web` chart. `osf-preprints`, `osf-registries`, and `osf-reviews` will be very similar.

```yaml
ember:
  replicaCount: 1

  antiAffinity: soft

  budget:
    minAvailable: 0

  image:
    repository: quay.io/centerforopenscience/osf-web
    tag: master
    pullPolicy: Always

  resources:
    limits:
      cpu: 1
      # memory: 128Mi
    requests:
      cpu: "0"
      memory: 128Mi

  nginx:
    image:
      repository: quay.io/centerforopenscience/nginx
      tag: master
      pullPolicy: Always

    resources:
      limits:
        cpu: 1
        # memory: 128Mi
      requests:
        cpu: "0"
        memory: 128Mi

  configFiles:
    config.json: |-
      {
          "environment": "production",
          "sentryDSN": "<SENTRY_DSN_PUBLIC>",
          "OSF": {
              "backend": "test",
              "url": "https://dev5.rcos.nii.ac.jp/",
              "apiUrl": "https://api.dev5.rcos.nii.ac.jp",
              "renderUrl": "https://mfr.dev5.rcos.nii.ac.jp/render",
              "waterbutlerUrl": "https://files.dev5.rcos.nii.ac.jp/",
              "helpUrl": "http://help.osf.io",
              "cookieLoginUrl": "https://accounts.dev5.rcos.nii.ac.jp/login",
              "oauthUrl": "https://accounts.dev5.rcos.nii.ac.jp/oauth2/authorize",
              "shareBaseUrl": "https://staging-share.osf.io/",
              "shareApiUrl": "https://staging-share.osf.io/api/v2",
              "shareSearchUrl": "https://staging-share.osf.io/api/v2/search/creativeworks/_search",
              "isLocal": false
          },
      }
```
